server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ems
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

all:
  prefix: "[Prod]"

logging:
  file:
    name: C:/logging-eshop/prod-env/emsProdLog.log
  logback:
    rollingpolicy:
      clean-history-on-start: true

